---

services:
  hugo-blog:
    image: nginx:latest
    container_name: hugo-blog
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hugo-network

networks:
  hugo-network:
    driver: bridge

